name: docker

on:
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'synchronize']
  schedule:
    # Every Monday at 9AM UTC (Yarik apparently did cron spec incorrectly somewhere)
    - cron: "0 9 * * 1"

jobs:
  info:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Updating and upgrading brew
        if: matrix.os == 'macos-latest'
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew --version
      - name: Install and start docker
        if: matrix.os == 'macos-latest'
        run: |
          # for the docker cli
          brew install docker
          # installed by default
          colima start
          docker ps
      - name: Test docker
        run: |
          docker version
          docker info
