name: docker

on:
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'synchronize']
  schedule:
    # Every Monday at 9AM UTC (Yarik apparently did cron spec incorrectly somewhere)
    - cron: "0 9 * * 1"

jobs:
  info:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Updating and upgrading brew
        if: startsWith(matrix.os, 'macos-')
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew --version
      - name: Install and start docker
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install --cask docker
          open /Applications/Docker.app
          while ! docker system info > /dev/null 2>&1; do
              echo "Waiting for Docker to launch..."
              sleep 5
          done
          docker ps
      - name: Test docker
        run: |
          docker version
          docker info
          docker run --rm bids/validator --help
